USE [master]
GO

/****** Object:  Database [Agenda]    Script Date: 22/11/2018 14:58:50 ******/
CREATE DATABASE [Agenda]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Agenda', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Agenda.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Agenda_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Agenda_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Agenda] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Agenda].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Agenda] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Agenda] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Agenda] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Agenda] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Agenda] SET ARITHABORT OFF 
GO

ALTER DATABASE [Agenda] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Agenda] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Agenda] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Agenda] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Agenda] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Agenda] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Agenda] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Agenda] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Agenda] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Agenda] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Agenda] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Agenda] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Agenda] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Agenda] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Agenda] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Agenda] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Agenda] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Agenda] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Agenda] SET  MULTI_USER 
GO

ALTER DATABASE [Agenda] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Agenda] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Agenda] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Agenda] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Agenda] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Agenda] SET  READ_WRITE 
GO


