//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agenda.Service.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Celular deve conter 11 caracteres.
        /// </summary>
        internal static string CelularLength {
            get {
                return ResourceManager.GetString("CelularLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Celular é obrigatório.
        /// </summary>
        internal static string CelularNotEmpty {
            get {
                return ResourceManager.GetString("CelularNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Celular é obrigatório.
        /// </summary>
        internal static string CelularNotNull {
            get {
                return ResourceManager.GetString("CelularNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é inválido.
        /// </summary>
        internal static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF deve conter 11 caracteres.
        /// </summary>
        internal static string CPFLength {
            get {
                return ResourceManager.GetString("CPFLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        internal static string CPFNotIsEmpty {
            get {
                return ResourceManager.GetString("CPFNotIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório.
        /// </summary>
        internal static string CPFNotNull {
            get {
                return ResourceManager.GetString("CPFNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail é inválido.
        /// </summary>
        internal static string EmailIvalido {
            get {
                return ResourceManager.GetString("EmailIvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail precisa ter no máximo 150 caracteres.
        /// </summary>
        internal static string EmailMaximumLength150 {
            get {
                return ResourceManager.GetString("EmailMaximumLength150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail precisa ter no mínimo 6 caracteres.
        /// </summary>
        internal static string EmailMinimumLength6 {
            get {
                return ResourceManager.GetString("EmailMinimumLength6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail é obrigatório.
        /// </summary>
        internal static string EmailNotEmpty {
            get {
                return ResourceManager.GetString("EmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O E-mail é obrigatório.
        /// </summary>
        internal static string EmailNotNull {
            get {
                return ResourceManager.GetString("EmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome precisa ter no máximo 100 caracteres.
        /// </summary>
        internal static string NomeMaximumLength100 {
            get {
                return ResourceManager.GetString("NomeMaximumLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome precisa ter no máximo 50 caracteres.
        /// </summary>
        internal static string NomeMaximumLength50 {
            get {
                return ResourceManager.GetString("NomeMaximumLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome precisa ter no mínimo 2 caracteres.
        /// </summary>
        internal static string NomeMinimumLength2 {
            get {
                return ResourceManager.GetString("NomeMinimumLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome é obrigatório.
        /// </summary>
        internal static string NomeNotEmpty {
            get {
                return ResourceManager.GetString("NomeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome é obrigatório.
        /// </summary>
        internal static string NomeNotNull {
            get {
                return ResourceManager.GetString("NomeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha Confirmação deve ser igual a Senha.
        /// </summary>
        internal static string SenhaConfirmacaoEqualsSenha {
            get {
                return ResourceManager.GetString("SenhaConfirmacaoEqualsSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha Confirmação ter no máximo 20 caracteres.
        /// </summary>
        internal static string SenhaConfirmacaoMaximumLength20 {
            get {
                return ResourceManager.GetString("SenhaConfirmacaoMaximumLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha Confirmação precisa ter no mínimo 6 caracteres.
        /// </summary>
        internal static string SenhaConfirmacaoMinimumLength6 {
            get {
                return ResourceManager.GetString("SenhaConfirmacaoMinimumLength6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha Confirmação é obrigatória.
        /// </summary>
        internal static string SenhaConfirmacaoNotEmpty {
            get {
                return ResourceManager.GetString("SenhaConfirmacaoNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha Confirmação é obrigatória.
        /// </summary>
        internal static string SenhaConfirmacaoNotNull {
            get {
                return ResourceManager.GetString("SenhaConfirmacaoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha precisa ter no máximo 20 caracteres.
        /// </summary>
        internal static string SenhaMaximumLength20 {
            get {
                return ResourceManager.GetString("SenhaMaximumLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha precisa ter no mínimo 6 caracteres.
        /// </summary>
        internal static string SenhaMinimumLength6 {
            get {
                return ResourceManager.GetString("SenhaMinimumLength6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha é obrigatória.
        /// </summary>
        internal static string SenhaNotEmpty {
            get {
                return ResourceManager.GetString("SenhaNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha é obrigatória.
        /// </summary>
        internal static string SenhaNotNull {
            get {
                return ResourceManager.GetString("SenhaNotNull", resourceCulture);
            }
        }
    }
}
